<a href="https://colab.research.google.com/github/KunalKaushikAI/unbxd_tpm_gpt/blob/main/product_comparision_unbxd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
from google.colab import drive

In [2]:
# Mount Google Drive
drive.mount('/content/drive')

Mounted at /content/drive

In [11]:
input_file_path = "/content/drive/My Drive/product_export/magento_producto_export.csv"  # Replace with your actual file path
output_file_path = "/content/drive/My Drive/product_export/filtered_data.csv"  # Replace with your actual output path

In [12]:
headers_to_keep = ["entityId", "sku", "visibility", "status", "typeId"]

In [13]:
unique_df = pd.DataFrame(columns=headers_to_keep)

In [15]:
unique_df

Empty DataFrame
Columns: [entityId, sku, visibility, status, typeId]
Index: []

In [16]:
df = pd.read_csv(input_file_path)

<ipython-input-16-1532df7d128b>:1: DtypeWarning: Columns (1,4,8,15,18,21,22,23,25,26,27,37,47,50,53,54,55,56,57,58,59,60,61,62,65,66,67,68,69,70,71,72,75,76,77,78,79,80,81,82,83,85,86,87,92,94,95,96,97,99,100,105,136,137,138,145,146) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(input_file_path)

In [17]:
df

,sku,store_view_code,attribute_set_code,product_type,categories,product_websites,name,description,short_description,weight,...,giftcard_is_redeemable,use_config_lifetime,giftcard_lifetime,use_config_allow_message,giftcard_allow_message,use_config_email_template,giftcard_email_template,associated_skus,downloadable_links,downloadable_samples
0,JRI03240-YC1A-000000000-00_0003,NaN,Variation1,simple,NaN,base,JRI03240-YC1A-000000000-00_0003,NaN,<p>Jokia Star Burst Ring For Women. Set in 18 ...,2.44,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,JRI03240-YC1A-000000000-00_0003,default,Variation1,simple,NaN,NaN,NaN,NaN,<p>Jokia Star Burst Ring For Women. Set in 18 ...,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,JRI03240-YC1A-000000000-00_0003,en_ca,Variation1,simple,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,JRI03240-YC1A-000000000-00_03.5,NaN,Variation1,simple,NaN,base,JRI03240-YC1A-000000000-00_03.5,NaN,<p>Jokia Star Burst Ring For Women. Set in 18 ...,2.49,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,JRI03240-YC1A-000000000-00_03.5,default,Variation1,simple,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
331196,ff2455af-0c9b-4c11-9491-b9f2234faebb,NaN,Solitaire,simple,Default Category/Solitaire Finder,base,Carat Round Diamond-0.61,NaN,NaN,0.61,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
331197,ff2bb6a9-ccc4-45ae-90c6-705a6ef54596,NaN,Solitaire,simple,Default Category/Solitaire Finder,base,Carat Round Diamond-0.6,NaN,NaN,0.60,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
331198,ffd20967-6324-44c9-a99d-4ca6d0f95658,NaN,Solitaire,simple,Default Category/Solitaire Finder,base,Carat Round Diamond-0.6,NaN,NaN,0.60,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
331199,ffecdeef-cff6-4f45-9e33-e6117fc26f9b,NaN,Solitaire,simple,Default Category/Solitaire Finder,base,Carat Pear Diamond-0.6,NaN,NaN,0.60,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
331200,fff5bc93-18aa-465f-b1f8-e59c9732009c,NaN,Solitaire,simple,Default Category/Solitaire Finder,base,Carat Round Diamond-0.6,NaN,NaN,0.60,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [32]:
columns_to_find = [ "sku","visibility", "store_view_code", "product_type","product_websites","is_in_stock","out_of_stock_qty"]

In [33]:
df2 = df[columns_to_find]

In [34]:
df2

,sku,visibility,store_view_code,product_type,product_websites,is_in_stock,out_of_stock_qty
0,JRI03240-YC1A-000000000-00_0003,Not Visible Individually,NaN,simple,base,1.0,0.0
1,JRI03240-YC1A-000000000-00_0003,NaN,default,simple,NaN,NaN,NaN
2,JRI03240-YC1A-000000000-00_0003,NaN,en_ca,simple,NaN,NaN,NaN
3,JRI03240-YC1A-000000000-00_03.5,Not Visible Individually,NaN,simple,base,1.0,0.0
4,JRI03240-YC1A-000000000-00_03.5,NaN,default,simple,NaN,NaN,NaN
...,...,...,...,...,...,...,...
331196,ff2455af-0c9b-4c11-9491-b9f2234faebb,"Catalog, Search",NaN,simple,base,1.0,0.0
331197,ff2bb6a9-ccc4-45ae-90c6-705a6ef54596,"Catalog, Search",NaN,simple,base,1.0,0.0
331198,ffd20967-6324-44c9-a99d-4ca6d0f95658,"Catalog, Search",NaN,simple,base,1.0,0.0
331199,ffecdeef-cff6-4f45-9e33-e6117fc26f9b,"Catalog, Search",NaN,simple,base,1.0,0.0
331200,fff5bc93-18aa-465f-b1f8-e59c9732009c,"Catalog, Search",NaN,simple,base,1.0,0.0

In [35]:
df2.to_csv(output_file_path, index=False)

In [36]:
df2.tail(100)

,sku,visibility,store_view_code,product_type,product_websites,is_in_stock,out_of_stock_qty
331101,c542c8b9-58db-4415-b057-9653b4494b52,"Catalog, Search",NaN,simple,base,1.0,0.0
331102,c5a19035-50bf-4d1c-b0b9-850bae671f78,"Catalog, Search",NaN,simple,base,1.0,0.0
331103,c64bd057-3874-49ea-bdc6-821f90079504,"Catalog, Search",NaN,simple,base,1.0,0.0
331104,c6599cb8-82f5-4012-9595-d9099e274a75,"Catalog, Search",NaN,simple,base,1.0,0.0
331105,c7726cb0-fd7b-4635-908d-7b782ca71d3d,"Catalog, Search",NaN,simple,base,1.0,0.0
...,...,...,...,...,...,...,...
331196,ff2455af-0c9b-4c11-9491-b9f2234faebb,"Catalog, Search",NaN,simple,base,1.0,0.0
331197,ff2bb6a9-ccc4-45ae-90c6-705a6ef54596,"Catalog, Search",NaN,simple,base,1.0,0.0
331198,ffd20967-6324-44c9-a99d-4ca6d0f95658,"Catalog, Search",NaN,simple,base,1.0,0.0
331199,ffecdeef-cff6-4f45-9e33-e6117fc26f9b,"Catalog, Search",NaN,simple,base,1.0,0.0
331200,fff5bc93-18aa-465f-b1f8-e59c9732009c,"Catalog, Search",NaN,simple,base,1.0,0.0

In [44]:
file1_path = "/content/drive/My Drive/product_export/filtered_data.csv"
file2_path = "/content/drive/My Drive/product_export/final.csv"

In [45]:
df_caratlane = pd.read_csv(file1_path)
df_unbxd = pd.read_csv(file2_path)

In [47]:
merged_df = pd.merge(df_caratlane, df_unbxd, on='sku', how='outer', indicator=True)

In [55]:
difference_df = merged_df[merged_df['_merge'] != 'both']

In [56]:
difference_df = difference_df.drop(columns='_merge')

In [57]:
difference_df = difference_df.drop_duplicates(subset='sku')

In [59]:
output_file_path = "/content/drive/My Drive/product_export/difference_no_duplicates.csv"  # Replace with your actual output path

In [60]:
difference_df.to_csv(output_file_path, index=False)